### ISSUE TITLE
Some tags are empty in our database

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#130]
Example: https://ccsearch.creativecommons.org/photos/15621775

Error:
```
Traceback (most recent call last):                                                                                    
  File "/usr/local/lib/python3.7/site-packages/rest_framework/fields.py", line 441, in get_attribute                  
    return get_attribute(instance, self.source_attrs)                                                                 
  File "/usr/local/lib/python3.7/site-packages/rest_framework/fields.py", line 98, in get_attribute                   
    instance = instance[attr]                                                                                         
KeyError: 'name' 
```

Tags for this image (note the empty tag):
```
15621775 | [{}, {"name": "business", "accuracy": 0.97734, "provider": "clarifai"}, {"name": "man", "accuracy": 0.93226, "provider": "clarifai"}, {"name": "paper", "accuracy": 0.89205, "provider": "clarifai"}, {
"name": "presentation", "accuracy": 0.89086, "provider": "clarifai"}, {"name": "people", "accuracy": 0.86843, "provider": "clarifai"}, {"name": "contemporary", "accuracy": 0.85604, "provider": "clarifai"}, {"nam
e": "identity", "accuracy": 0.84483, "provider": "clarifai"}, {"name": "facts", "accuracy": 0.81679, "provider": "clarifai"}, {"name": "blank", "accuracy": 0.81582, "provider": "clarifai"}, {"name": "intelligenc
e", "accuracy": 0.81183, "provider": "clarifai"}, {"name": "bill", "accuracy": 0.80434, "provider": "clarifai"}, {"name": "achievement", "accuracy": 0.7914, "provider": "clarifai"}, {"name": "horizontal", "accur
acy": 0.78989, "provider": "clarifai"}, {"name": "education", "accuracy": 0.77418, "provider": "clarifai"}, {"name": "template", "accuracy": 0.77406, "provider": "clarifai"}, {"name": "fine-looking", "accuracy":
 0.77116, "provider": "clarifai"}, {"name": "indoors", "accuracy": 0.76115, "provider": "clarifai"}, {"name": "company", "accuracy": 0.75583, "provider": "clarifai"}, {"name": "looking", "accuracy": 0.75398, "pr
ovider": "clarifai"}, {"name": "banner", "accuracy": 0.74502, "provider": "clarifai"}]
```

**Comment by aldenstpage** [comment]
The API handles malformed tag data without an internal server error now. The front end renders the empty tag. To resolve this, @sclachar is going to fix the bad tag data in our intermediary database, which I will then synchronize to production.

**Comment by sclachar** [comment]
resolved, @aldenstpage please sync to prod.

**Comment by aldenstpage** [comment]
Synced in production
