### ISSUE TITLE
Handle search phase execution exceptions gracefully

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#406]
Search phase execution exceptions throw an error 500, when they should instead raise an InputError.

```
ValueError: RequestError(400, 'search_phase_execution_exception', 'Failed to parse query [hello!]')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/cccatalog-api/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/www/cccatalog-api/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/cccatalog-api/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/cccatalog-api/.venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/cccatalog-api/.venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/cccatalog-api/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/cccatalog-api/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/cccatalog-api/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/var/www/cccatalog-api/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "./cccatalog/api/views/image_views.py", line 88, in get
    return input_error_response(str(value_error))
  File "./cccatalog/api/utils/exceptions.py", line 16, in input_error_response
    error = errors[_field]
TypeError: string indices must be integers
```

**Comment by HAKSOAT** [comment]
Hello @aldenstpage I am new here, but I'll like to help with this.

**Comment by aldenstpage** [comment]
Feel free to take it on! I would like the end result to look something more like this:
Request: https://api-dev.creativecommons.engineering/v1/images?q=test&li=\[\]
Response:
```
{
   "detail" : "Invalid input given for field li. Hint: Parameter 'li' is deprecated in this release of the API. Use 'license' instead.",
   "field" : "li",
   "error_type" : "InputError"
}
```

Here's an example of the case we want to fix: https://api.creativecommons.engineering/v1/images?q=hello!
So, there would be a `detail`, a `field` (`q`), and an `error_type` (InputError), and the message would relay the "Failed to parse query [hello!] message.

**Comment by HAKSOAT** [comment]
Great. Thanks for the guidance.

**Comment by HAKSOAT** [comment]
I'm having issues setting up the environment, to even know if my code works. I'm using Docker Toolbox.

**Comment by HAKSOAT** [comment]
I setup a VM and did the setup there. The environment works now, back on track.
