### ISSUE TITLE
500 Response for digitalt museum provider

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/cccatalog-api#509]
Currently returning a 500 error, and subsequently no results on the frontend. 

Failed API route: https://api.creativecommons.engineering/v1/images?format=json&source=digitaltmuseum

Empty front-end route: https://search.creativecommons.org/collections/digitaltmuseum

**Comment by aldenstpage** [comment]
It looks like the problem is that the thumbnail proxy expects a file extension when there is none to be found for images sourced from digitaltmuseum.

```
Internal Server Error: /v1/images
Traceback (most recent call last):
  File "/var/www/cccatalog-api/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/www/cccatalog-api/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/cccatalog-api/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/cccatalog-api/.venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/cccatalog-api/.venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/cccatalog-api/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/cccatalog-api/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/cccatalog-api/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/var/www/cccatalog-api/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "./cccatalog/api/views/image_views.py", line 89, in get
    page=page_param
  File "./cccatalog/api/controllers/search_controller.py", line 349, in search
    filter_dead
  File "./cccatalog/api/controllers/search_controller.py", line 135, in _post_process_results
    'identifier': "{}.{}".format(res["identifier"], ext)
  File "/var/www/cccatalog-api/.venv/lib/python3.7/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/var/www/cccatalog-api/.venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'thumbs' with keyword arguments '{'identifier': '4b17bb11-e2f8-4210-ad64-c6aeb29e6ff4.org/image/03347xEG5oUk?dimension=1200x1200'}' not found. 1 pattern(s) tried: ['v1/thumbs/(?P<identifier>[^/]+)$']
```
